name: Javascript Lint with eslint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install eslint
      run: npm install eslint
    - name: Run ESLint
      run: eslint . --ext .js
