name: Javascript Lint with eslint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install eslint with yarn
      run: yarn add eslint
    - name: Run ESLint
      run: yarn run eslint . --ext .js
